PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Shifts;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Usergroups;

CREATE TABLE IF NOT EXISTS Users(
name NVCHAR(20) NOT NULL UNIQUE,
username NVCHAR(20) NOT NULL UNIQUE,
email NVCHAR(50) NOT NULL UNIQUE,
password NVCHAR(100) NOT NULL,
squestion NVCHAR(100) NOT NULL,
sanswer NVCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS Shifts(
title NVCHAR(30),
description NVCHAR(30),
allDay BOOLEAN DEFAULT FALSE,
recurring BOOLEAN DEFAULT FALSE,
start DATE NOT NULL,
end DATE NOT NULL);

CREATE TABLE IF NOT EXISTS Groups(
groupname NVCHAR(20) NOT NULL UNIQUE,
squestion NVCHAR(100) NOT NULL,
sanswer NVCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS Usergroups(
userid INTEGER(10) NOT NULL,
groupid INTEGER(10) NOT NULL,
permissionlevel INTEGER(2) NOT NULL);

COMMIT;
